import type { Metadata } from 'next'
import '../../globals.css'
import AdminLayout from '@/components/templates/AdminLayout'

export const metadata: Metadata = {
  title: 'Menu Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <AdminLayout>{children}</AdminLayout>
}
